src/gmgcozone/GMGColor/Controllers/ApprovalWorkflowController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using GMGColor.Common;
using GMGColorBusinessLogic;
using GMGColorDAL;
using GMGColorDAL.CustomModels.ApprovalWorkflows;
using System.Web.Script.Serialization;
using System.Net;
using AutoMapper;
using GMGColor.Hubs;
using GMGColorDAL.CustomModels;
using GMGColorDAL.CustomModels.Api;
using Microsoft.AspNet.SignalR;
using GMG.CoZone.Collaborate.Interfaces;
using GMG.CoZone.Collaborate.Services.Soad_State;
using GMG.CoZone.Common.Interfaces;

namespace GMGColor.Controllers
{
    public class ApprovalWorkflowController : BaseController
    {
        #region Fileds

        private const string SearchApprovalWorkflows = "SearchApprovalWorkflows";

        private readonly ISoadStateService _soadStateService;

        public ApprovalWorkflowController(ISoadStateService soadStateService, IDownloadService downlaodService, IMapper mapper) : base(downlaodService, mapper)
        {
            _soadStateService = soadStateService;
        }
        #endregion

        #region GET Actions
        //
        // GET: /ApprovalWorkflow/
        [HttpGet]
        public ActionResult ApprovalWorkflows()
        {
            var model = new ApprovalWorkflowDashboardModel {ApprovalWorkflow = new ApprovalWorkflowModel()};

            if (TempData[SearchApprovalWorkflows] is string)
            {
                model.SearchText = TempData[SearchApprovalWorkflows] as string;
                model.ApprovalWorkflows = ApprovalWorkflowBL.GetApprovalWorkflows(LoggedAccount.ID, Context, model.SearchText);
            }
            else
            {
                model.ApprovalWorkflows = ApprovalWorkflowBL.GetApprovalWorkflows(LoggedAccount.ID, Context);
            }

            return View("ApprovalWorkflows", model);
        }

        [HttpGet]
        public ActionResult AddEditApprovalPhase(int? selectedApprovalWorkflow, int? selectedPhase, bool copyPhase = false)
        {
            var model = new PhaseViewModel {ApprovalWorkflow = selectedApprovalWorkflow.GetValueOrDefault()};
            if (selectedPhase.HasValue)
            {
                if (!DALUtils.IsFromCurrentAccount<GMGColorDAL.ApprovalPhase>(selectedPhase.Value, LoggedAccount.ID, Context))
                {
                    return RedirectToAction("Unauthorised", "Error");
                }

                model = ApprovalWorkflowBL.GetPhaseDetails(LoggedAccount, selectedPhase.Value, Context);
                model.ApprovalPhaseCollaboratorInfo.LoadPhaseCollaborats(selectedPhase.Value, Context);

                if (copyPhase)
                {
                    model.IsCopyPhase = true;
                    model.PhaseName = string.Empty;
                    model.ApprovalWorkflows = ApprovalWorkflowBL.GetApprovalWorkflows(LoggedAccount.ID, Context);
                }
               
                model.ID = selectedPhase.Value;
            }
            else
            {
                ApprovalWorkflowBL.PopulateStaticData(model, LoggedAccount, Context);
            }
            model.LoggedAccount = LoggedAccount;
           
            return View("AddEditPhase", model);
        }

        [HttpGet]
        public ActionResult AddEditAdHocWorkflowPhase()
        {
            var model = new PhaseViewModel();
            ApprovalWorkflowBL.PopulateStaticData(model, LoggedAccount, Context);
            model.LoggedAccount = LoggedAccount;
            model.isAdHocWorkflow = true;
            var jsonResult = Json(
                new
                {
                    Status = 200,
                    Content = RenderViewToString(this, "~/Views/Approvals/_AddAdHocWorkflow.cshtml", LoggedUser.ID, model)
                },
                JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpGet]
        public JsonResult IsApprovalWorkflowName_Available(ApprovalWorkflowDashboardModel model)
        {
            var workflow = model.ApprovalWorkflow;
            if (ApprovalWorkflow.IsApprovalWorkflowNameUnique(LoggedAccount.ID, workflow.Name,
                workflow.ID, Context))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            string infoMsg = String.Format(Resources.Resources.lblNameIsNotAvailable, workflow.Name);

            return Json(infoMsg, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult IsApprovalPhaseNameUnique(PhaseViewModel model)
        {
            var workflowId = model.IsCopyPhase ? model.SelectedApprovalWorkflow : model.ApprovalWorkflow;
            if (ApprovalPhase.IsApprovalPhaseNameUnique(workflowId, model.PhaseName, model.ID, Context))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            string infoMsg = String.Format(Resources.Resources.lblNameIsNotAvailable, model.PhaseName);

            return Json(infoMsg, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetApprovalWorkflowPhases(int? workflowId)
        {
            try
            {
                if (workflowId != null)
                {
                    if (!DALUtils.IsFromCurrentAccount<GMGColorDAL.ApprovalWorkflow>(workflowId.Value, LoggedAccount.ID, Context))
                    {
                        return RedirectToAction("Unauthorised", "Error");
                    }

                    ApprovalWorkflowPhasesDashboardModel workflowPhases = ApprovalWorkflowBL.GetApprovalWorkflowPhasesById(workflowId.Value, LoggedAccount.ID, Context);
                    return Json(
                        new
                            {
                                Status = 200,
                                Content = RenderViewToString(this, "ApprovalWorkflowPhases", LoggedUser.ID, workflowPhases)
                            },
                        JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                GMGColorLogging.log.ErrorFormat(ex, LoggedAccount.ID,
                   "ApprovalWorkflowController.GetApprovalWorkflowPhases : error return creating json result. {0} StackTrace {1}", ex.Message, ex.StackTrace);
            }
            return Json(
                    new
                    {
                        Status = 300,
                        Content = Resources.Resources.errCannotRetrieveApprovalWorkflowPhases
                    },
                    JsonRequestBehavior.AllowGet);
            
        }
        #endregion

        #region POST Action

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "SearchApprovalWorkflows")]
        public ActionResult Search(ApprovalWorkflowDashboardModel model)
        {
            string s = (model != null && model.SearchText != null) ? model.SearchText : string.Empty;
            TempData[SearchApprovalWorkflows] = s;

            return RedirectToAction("ApprovalWorkflows");
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "DeleteApprovalWorkflow")]
        public ActionResult DeleteApprovalWorkflow(int? selectedApprovalWorflowId)
        {
            try
            {
                if (selectedApprovalWorflowId.HasValue && !DALUtils.IsFromCurrentAccount<ApprovalWorkflow>(selectedApprovalWorflowId.Value, LoggedAccount.ID, Context))
                {
                    return RedirectToAction("Unauthorised", "Error");
                }

                var approvalWorkflow = Context.ApprovalWorkflows.FirstOrDefault(w => w.ID == selectedApprovalWorflowId.Value);
                if (approvalWorkflow != null)
                {
                    foreach (var phase in approvalWorkflow.ApprovalPhases.ToList())
                    {
                        ApprovalWorkflowBL.DeleteApprovalPhase(phase.ID, Context);
                    }

                    Context.ApprovalWorkflows.Remove(approvalWorkflow);
                }
                Context.SaveChanges();
            }
            catch (Exception ex)
            {
                GMGColorLogging.log.ErrorFormat(ex, this.LoggedAccount.ID, "ApprovalWorkflowController.DeleteApprovalWorkflow : Deletet approval workflow failed. {0}", ex.Message);
            }
            return RedirectToAction("ApprovalWorkflows");
        }

        [HttpPost]
        public ActionResult AddEditApprovalWorkflow(ApprovalWorkflowDashboardModel model, int? page)
        {
            try
            {
                #region Validations

                if (model.ApprovalWorkflow.ID > 0 && !DALUtils.IsFromCurrentAccount<ApprovalWorkflow>(model.ApprovalWorkflow.ID, LoggedAccount.ID, Context))
                {
                    return RedirectToAction("Unauthorised", "Error");
                }

                if (!CheckIsValidHtml(model.ApprovalWorkflow.Name))
                {
                    return RedirectToAction("XSSRequestValidation", "Error");
                }

                #endregion

                #region Add/Update Approval Workflow

                ApprovalWorkflowBL.AddOrUpdateWorkflow(model.ApprovalWorkflow, LoggedAccount.ID, LoggedUser.ID, Context);
                Context.SaveChanges();

                #endregion

                ViewBag.Page = page;
            }
            catch (DbEntityValidationException ex)
            {
                DALUtils.LogDbEntityValidationException(ex);
            }
            catch (Exception ex)
            {

src/gmgcozone/GMGColor/Views/ApprovalWorkflow/AddEditPhase.cshtml
@using GMGColor.HtmlHelpers
@using GMGColor.Resources
@using GMGColorDAL
@using GMGColorDAL.Common
@model GMGColorDAL.CustomModels.ApprovalWorkflows.PhaseViewModel

@{
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
    Bundles.Reference("widget");
    Bundles.Reference("approvalPhase");
    Bundles.Reference("datetimepicker");
    GMGColorBusinessLogic.DbContextBL context = HttpContext.Current.Items[GMGColorDAL.DALUtils.DatabaseContext] as GMGColorBusinessLogic.DbContextBL;
}

<p class="breadcrumb">
    <a href="@Url.Action("ApprovalWorkflows", "ApprovalWorkflow")">@Resources.lblApprovalWorkflowsTitle</a>
</p>
<div class="widget-header">
    <h3>@(Model.IsCopyPhase ? Resources.lblCopyExistingApprovalPhase : (Model.ID > 0 ? Resources.lblEditPhase : Resources.lblAddNewPhase))</h3>
</div>

<!-- /widget-header -->
<div class="widget-content">
    <div class="row-fluid">
        @using (Html.BeginForm("AddEditApprovalPhase", "ApprovalWorkflow", FormMethod.Post, new { @class = "form-horizontal", @id = "phaseForm" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            @Html.HiddenFor(m => m.ID, new { @data_val = false })
            @Html.HiddenFor(m => m.ApprovalWorkflow, new { @data_val = false })
            @Html.HiddenFor(m => m.Position, new { @data_val = false })
            @Html.HiddenFor(m => m.IsCopyPhase, new { @data_val = false })

            if(Model.ID > 0){
                <div id="phaseDetailsPropagationMsg" class="alert alert-warning" role="alert">
                        @Resources.msgPhaseDetailsPropagation
                </div>
            }
            if (Model.IsCopyPhase)
            {
                <div id="approvalWorkflow" class="control-group">
                    <label class="control-label required">@Resources.lblExistingWorkflow</label>
                    <div class="controls">
                        @Html.DropDownListFor(m => m.SelectedApprovalWorkflow, new SelectList(Model.ApprovalWorkflows, "ID", "Name"), Resources.lblSelectOne)
                        @Html.ValidationMessageFor(m => m.SelectedApprovalWorkflow)
                    </div>
                </div> 
            }
            <div class="widget">
                @Html.Partial("_AddEditPhaseDetails", Model)
            </div>
            
            <div class="form-actions">
                <button id="savePhase" type="submit" class="btn btn-primary pull-right" data-text="@Resources.btnUploadSettingsSaveChanges" data-loading-text="@Resources.btnSaving">@Resources.btnUploadSettingsSaveChanges</button>
                    @Html.Image("imgSavingLoader", "~/Content/img/loading-icon.gif", @Resources.lblLoading, new { @class = "hide pull-right" }, 30, 30)
            </div>
        }
    <!-- /row-fluid -->
    </div>
    <!-- /widget-content -->
</div>
<!-- /widget -->

src/gmgcozone/GMGColor/Views/ApprovalWorkflow/ApprovalWorkflowPhases.cshtml
@model GMGColorDAL.CustomModels.ApprovalWorkflows.ApprovalWorkflowPhasesDashboardModel
@using GMGColor.Resources
@using GMGColorDAL.CustomModels
@{
    var workflowPhasesGroup = String.Format("approvalWorkflow{0}_Phases", Model.Workflow);
    var approvalWorkflowPhases = new WebGrid(Model.ApprovalWorkflowPhaseDetails);
}
<script src="../../Content/js/bootstrap/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="../../Content/js/approval-phase.js" type="text/javascript"></script>

@approvalWorkflowPhases.GetHtml(
    tableStyle: "table table-striped table-bordered",
    htmlAttributes: new { id = workflowPhasesGroup},
    columns:
        approvalWorkflowPhases.Columns(
            approvalWorkflowPhases.Column(format: @<text><ul class="pull-left upAndDownButtons" phase="@item.ID">
                                                             <li><a href="#" class="up" rel="nofollow"><i class="icon-angle-up"></i></a></li>
                                                             <li><a href="#" class="down" rel="nofollow"><i class="icon-angle-down"></i></a></li>
                                                         </ul>
                                                  </text>),
            approvalWorkflowPhases.Column(columnName: "Name", header: Resources.lblName, canSort: false, format: @<text><a href="@Url.Action("AddEditApprovalPhase", new { selectedPhase = item.ID})">@item.Name</a></text>),
            approvalWorkflowPhases.Column(columnName: "DecisionType", header: Resources.lblDecisionType, canSort: false, format: @<text>@item.DecisionType</text>),
            approvalWorkflowPhases.Column(columnName: "PrimaryDecisionMaker", header: Resources.lblPhasePDM, canSort: false, format: @<text>@item.PrimaryDecisionMaker</text>),
            approvalWorkflowPhases.Column(columnName: "ApprovalTrigger", header: Resources.lblApprovalTrigger, canSort: false, format: @<text>@item.ApprovalTrigger</text>),
            approvalWorkflowPhases.Column(format: @<text>@Html.Raw(GetActionButtons(item.ID))</text>)
            )
        )

@Html.Hidden("selectedPhase", 0, new { id = "hdnSelectedPhase", @data_val = false })

@{ DeleteConfirmation deleteUserConfirmation = new DeleteConfirmation(2, "DeleteApprovalPhase"); }
@Html.Partial("DeleteConfirmationDialog", deleteUserConfirmation)

@functions{
    private string GetActionButtons(int id)
    {
        System.Text.StringBuilder html = new System.Text.StringBuilder();
        html.Append("<div class=\"btn-group pull-right\">");
        html.Append("   <a href=\"javascript:void(0);\" data-toggle=\"dropdown\" class=\"btn btn-mini dropdown-toggle ellipsisButtonList\"><i class=\"icon-ellipsis-horizontal\"></i></a>");
        html.Append("   <ul class=\"dropdown-menu pull-right\">");
        html.Append("      <li><a href=" + @Url.Action("AddEditApprovalPhase", new { selectedPhase = id }) + "><i class=\"icon-pencil\"></i>" + Resources.btnEdit + "</a></li>");
        html.Append("      <li><a href=\"javascript:void(0);\" onclick=\"$('#hdnSelectedPhase')[0].value = " + id + ";$('#modelDialogDeleteConfirmation_2').modal({ backdrop: 'static', keyboard: false });\" rel=\"nofollow\" data-method=\"delete\" data-disable-with=\"Deleting...\" ><i class=\"icon-trash\"></i>" + Resources.btnDelete + "</a></li>");
        html.Append("      <li><a href=" + @Url.Action("AddEditApprovalPhase", new { selectedPhase = id, copyPhase = true }) + "><i class=\"icon-copy\"></i>" + Resources.btnCopyPhase + "</a></li>");
        html.Append("   </ul>");
        html.Append("</div>");

        return html.ToString();
    }
}

src/gmgcozone/GMGColor/Views/ApprovalWorkflow/ApprovalWorkflows.cshtml
@using GMGColor.Resources
@using GMGColorDAL.CustomModels
@model GMGColorDAL.CustomModels.ApprovalWorkflows.ApprovalWorkflowDashboardModel

@{
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
    Bundles.Reference("approvalWorkflow");
}

<div class="widget">
    <div class="widget-header">
            <ul class="widget-links">
                <li><a class="btn btn-primary" href="javascript:void(0)" onclick="$('#modalNewApprovalWorkflow').modal({ backdrop: 'static', keyboard: false });">@Resources.lblNewApprovalWorkflow</a></li>
            </ul>
        <h3>@ViewBag.Header @*<small>@ViewBag.HeaderSmall</small>*@</h3>
    </div>
    <!-- /widget-header -->
    <div class="widget-content">
        <div class="row-fluid">
            <div class="span3">
                @{Html.RenderAction("SecondaryNavigation", "Navigation");}
            </div>
            <div class="span9">
                @using (Html.BeginForm("ApprovalWorkflows", "ApprovalWorkflow", FormMethod.Post, new { @class = "form-horizontal dirtyignore", id = "formMain" }))
                {
                    @Html.AntiForgeryToken()
                    <div id="dvColorProofInstanaces" class="tab-pane">
                        @if (Model.ApprovalWorkflows.Count > 0 || !string.IsNullOrEmpty(Model.SearchText))
                        {
                            <legend>@Resources.lblApprovalWorkflowsTitle</legend>
                            <div class="well form-search clearboth">
                                <div class="input-append">
                                    @Html.Hidden("SearchText", "0", new { id = "hdnSearchText" })
                                    @Html.TextBoxFor(model => model.SearchText, new { id = "txtSearch", @class = "input-medium search-query" })
                                    <button id="btnSearchText" type="submit" class="btn cancel" name="action" value="SearchApprovalWorkflows" onclick="$('#hdnSearchText')[0].value = $('#txtSearch').val();">
                                        @Resources.btnSearch</button>
                                </div>
                            </div>
                            <div class="display-field">
                                @if (Model.ApprovalWorkflows.Count > 0)
                                {
                                    <div>
                                        <div id="errOccured" style="display: none;" class="validation-summary-errors">
                                            <ul>
                                                <li>@Resources.errServerError</li>
                                            </ul>
                                        </div>
                                        <table class="table table-striped table-bordered table-responsive resizable" id="workflowPhases">
                                            @foreach (var item in Model.ApprovalWorkflows)
                                            {
                                                <tr>
                                                    @if (item.HasPhases)
                                                    {
                                                        <td class="span10 accordion-toggle" id="@string.Format("trigger{0}", item.ID)" onclick="@string.Format("rowToogleWorkflow({0}, '{1}');", item.ID, @Url.Action("GetApprovalWorkflowPhases", new {workflowId = item.ID}))">
                                                            <i class="icon-caret-right icon"></i>
                                                            @item.Name
                                                        </td>
                                                    }
                                                    else
                                                    {
                                                        <td class="span10">
                                                            @item.Name
                                                        </td>
                                                    }
                                                    <td>
                                                        <div id="dvAction@((int)item.ID)" class="btn-group pull-right">
                                                            <a href="javascript:void(0);" data-toggle="dropdown" class="btn btn-mini dropdown-toggle ellipsisButtonList">
                                                                <i class="icon-ellipsis-horizontal"></i></a>
                                                            <ul class="dropdown-menu pull-right">
                                                                <li><a href="javascript:void(0);" onclick="renameApprovalWorkflow('@(item.Name)', @(item.ID), @(item.RerunWorkflow.ToString().ToLower()))" title="@Resources.btnEdit">
                                                                        <i class="icon-pencil"></i>&nbsp;@Resources.btnEdit</a> </li>
                                                                <li><a href="javascript:void(0);" onclick="$('#hdnApprovalWorflow')[0].value = @(item.ID);$('#modelDialogDeleteConfirmation_1').modal({ backdrop: 'static', keyboard: false });" rel="nofollow" data-method="delete">
                                                                        <i class="icon-trash"></i>&nbsp;@Resources.lblDelete</a> </li>
                                                                <li><a href="@Url.Action("AddEditApprovalPhase", new { selectedApprovalWorkflow = item.ID })" title="@Resources.lblAddNewPhase"><i class="icon-list-ol"></i>&nbsp;@Resources.lblAddNewPhase</a> </li>
                                                            </ul>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="hide" colspan="2" id="@string.Format("workflow{0}", item.ID)">
                                                        <img alt="Loading ..." height="30" id="@string.Format("imgWorkflowLoading{0}", item.ID)" src="@Url.Content("~/Content/img/loading-icon.gif")" width="30" />
                                                    </td>
                                                </tr>
                                            }
                                        </table>
                                    </div>
                                }
                            </div>
                            @Html.Hidden("selectedApprovalWorflowId", 0, new { id = "hdnApprovalWorflow" })
                            DeleteConfirmation deleteAccountConfirmation = new DeleteConfirmation(1, "DeleteApprovalWorkflow");
                            @Html.Partial("DeleteConfirmationDialog", deleteAccountConfirmation)
                        }
                        else
                        { 
                            <div class="row-fluid blank-state" visible="false">
                                <div class="span4 blank-state-icon">
                                    <i class="icon-th"></i>
                                </div>
                                <div class="span7">
                                    <h3>@Resources.lblAddYourFirstApprovalWorkflow</h3>
                                    <p>@Resources.lblYoyCanAddAsManyApprovalWorkflowsAsYouLike</p>
                                    <p>
                                        <a class="btn btn-primary" title="@Resources.lblAddYourFirstApprovalWorkflow" onclick=" $('#modalNewApprovalWorkflow').modal({ backdrop: 'static', keyboard: false });">@Resources.lblNewApprovalWorkflow</a>
                                    </p>
                                </div>
                            </div>
                        }
                    </div>
                }
                        
            </div>
        </div>
        <!-- /row-fluid -->
    </div>
    <!-- /widget-content -->
</div>
<!-- /widget -->


<div id="modalNewApprovalWorkflow" class="modal hide">
    @using (Html.BeginForm("AddEditApprovalWorkflow", "ApprovalWorkflow", FormMethod.Post, new { id = "formNewApprovalWorkflow", @class = "form-horizontal dirtyignore" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(mdl => mdl.ApprovalWorkflow.ID, new { @data_val = false, id = "hdnApprovalWorkflowId" })
        <div class="modal-header">
            <a href="javascript:void(0);" class="close" data-dismiss="modal" title="@Resources.btnClose" onclick="ResetModel();">&times;</a>
            <h3 class="create">@Resources.lblNewApprovalWorkflow</h3>
            <h3 class="rename hide">@Resources.lblEditApprovalWorkflow</h3>
        </div>
        @Html.ValidationSummary(true)
        <div class="modal-body">
            <div class="control-group">
                <label class="control-label">@Resources.lblName</label>
                <div class="controls">
                    @Html.TextBoxFor(mdl => mdl.ApprovalWorkflow.Name, new { @Value = Model.ApprovalWorkflow.Name })
                    @Html.ValidationMessageFor(mdl => mdl.ApprovalWorkflow.Name)
                </div>
            </div>
            <div class="control-group">
                <label class="control-label rerun-workflow-label">@Resources.lblRerunWorklfow</label>
                <span class="pull-left rerun-info-message" style="font-size: large;" data-original-title="@Resources.lblRerunWorklfowInfoMessage" rel="tooltip">
                    <i class="icon-exclamation-sign"></i>

                </span>
                @Html.CheckBoxFor(mdl => mdl.ApprovalWorkflow.RerunWorkflow, new { @class = "workflow-checkbox" })


            </div>
        </div>
       <div class="modal-footer">
           <button class="create btn btn-primary" data-loading-text="@Resources.btnSaving" type="submit" >@Resources.btnCreateFolder</button>
           <button class="rename hide btn btn-primary" data-loading-text="@Resources.btnSaving" type="submit">@Resources.btnSave</button>
       </div>
    }
</div>