src/gmgcozone/GMGColor/Controllers/ApplicationSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using AutoMapper;
using GMG.CoZone.Common;
using GMG.CoZone.Common.Interfaces;
using GMGColor.Common;
using GMGColorBusinessLogic;
using GMGColorDAL;
using GMGColorDAL.CustomModels;
using AppModule = GMGColorDAL.AppModule;

namespace GMGColor.Controllers
{
    public class ApplicationSettingsController : BaseController
    {
        public ApplicationSettingsController(IDownloadService downlaodService, IMapper mapper) : base(downlaodService, mapper) { }

        // GET: ApplicationSettings
        public ActionResult Index()
        {
            try
            { 
                var model =  ThemeBL.GetApprovalTypeColorScheme(Context);
                return View("Index", model);
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult UpdateTheme(List<ApprovalTypeModel> model)
        {
            try
            {
                ThemeBL.UpdateApprovalTypeColorScheme(model, Context);
            }
            catch (Exception ex)
            {
                GMGColorLogging.log.Error("ApplicationSettings.UpdateTheme : Exception details : " + ex.Message, ex);
            }

            return RedirectToAction("Index");
        }
    }
}

src/gmgcozone/GMGColor/Views/ApplicationSettings/Index.cshtml
@model List<GMGColorDAL.CustomModels.ApprovalTypeModel>
@using GMGColor.Resources
@using GMGColor.HtmlHelpers;
@{
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
    Bundles.Reference("fileupload");
    Bundles.Reference("colorpicker");
    GMGColorBusinessLogic.DbContextBL context = HttpContext.Current.Items[GMGColorDAL.DALUtils.DatabaseContext] as GMGColorBusinessLogic.DbContextBL;
}

<div class="widget">
    <div class="widget-header">
        <h3>@ViewBag.Header@*&nbsp;<small>@ViewBag.HeaderSmall</small>*@</h3>
    </div>
    <!-- /widget-header -->
    <div class="widget-content">
        <div class="row-fluid">
            <div class="span3 accoutnSettingdNav">
                <ul class="nav nav-tabs nav-stacked">
                    <li class="active"><a href="Index">@Resources.lblApprovalType</a></li>
                </ul>
            </div>
            <div class="span9">
                @using (Html.BeginForm("UpdateTheme", "ApplicationSettings", FormMethod.Post, new { @class = "form-horizontal", id = "formInformation" }))
                {
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <legend>@Resources.lblApprovalType</legend>
                        <label>@Resources.txtApprovalTypeNote</label>
                        <div class="input-append color">
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                <div style="margin-right: 25px; position: relative; top: 3px; margin-bottom: 20px;">
                                    <label style="display: inline-block; text-align:right; width:50px; margin-right: 40px; position: relative; top: 3px;" class="colorSchemeGroup centerlabel">@Model[i].Name</label>
                                    <span style="margin-right: 10px;" class="colorSchemeGroup">
                                        @Html.TextBoxFor(m => m[i].FileTypes, new { @id = "FileTypes", @class = "", data_color_format = "rgb" })
                                    </span>
                                    <span class="colorSchemeGroup">
                                        @Html.TextBoxFor(m => m[i].Colour, new { @id = "themeHeader", @class = "colorPicker", data_color_format = "rgb" })
                                        <span class="add-on cursorPointer"><i class="cursorPointer" style="background-color: @Model[i].Colour"></i></span>
                                    </span>
                                </div>
                            }                            
                        </div>
                    </fieldset>

                    <div class="form-actions">
                        <input id="btnSaveChangesInformation" class="btn btn-primary" type="submit" value="@Resources.btnSaveChanges" data-loading-text="@Resources.btnSaving" />
                    </div>
                }

            </div>
        </div>
        <!-- /row-fluid -->
    </div>
    <!-- /widget-content -->
</div>
@{ Bundles.Reference("accountThemeScripts"); }

<!-- /widget -->