src/gmgcozone/GMGColor/Controllers/PersonalSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using AutoMapper;
using GMG.CoZone.Common.Interfaces;
using GMGColor.Common;
using GMGColorBusinessLogic;
using GMGColorDAL;
using GMGColorDAL.Common;
using GMGColorDAL.CustomModels;
using Microsoft.Web.Administration;


namespace GMGColor.Controllers
{
    public class PersonalSettingsController : BaseController
    {
        public PersonalSettingsController(IDownloadService downlaodService, IMapper mapper) : base(downlaodService, mapper) { }

        #region Fields

        private const string NotificationsKey = "Notifications";
        private const string PresetKey = "preset";
        private const string NotificationFrequencyKey = "notificationFrequency";
        private const string IncludeMyOwnActivityKey = "includeMyOwnActivity";
        #endregion

        #region Properties

        protected bool HasNotifications
        {
            get
            {
                bool n = false;
                try
                {
                    n = Session["HasNotifications_" + LoggedUser.ID] != null
                                ? Convert.ToBoolean(Session["HasNotifications_" + LoggedUser.ID])
                                : NotificationServiceBL.HasPersonalNotifications(LoggedUser.ID, Context);
                }
                catch (Exception)
                {
                    Session["HasNotifications_" + LoggedUser.ID] = n;
                }
                Session["HasNotifications_" + LoggedUser.ID] = n;
                return n;
            }
        }

        #endregion

        #region GET Actions

        [HttpGet]
        public ActionResult Index()
        {
            var objUserModel = new OwnerUser(this.LoggedUser, Context)
            {
                HasNotifications = HasNotifications
            };
            return View("Index", objUserModel);
        }

        [HttpGet]
        public ActionResult Photo()
        {
            var photoModel = new ChangePhoto(LoggedUser, LoggedUserTempFolderPath)
            {
                HasNotifications = HasNotifications
            };

            if (!DALUtils.IsFromCurrentAccount<GMGColorDAL.User>(photoModel.UserID, LoggedAccount.ID, Context))
            {
                return RedirectToAction("Unauthorised", "Error");
            }

            //Show color if logged account is not sys admin
            if (LoggedAccountType != AccountType.Type.GMGColor)
            {
                ViewBag.AvailableColors = UserBL.GetAvailableUserColors(LoggedUser.ID, LoggedAccount.ID, Context);
            }

            return View("Photo", photoModel);
        }

        [HttpGet]
        public ActionResult Password()
        {
            var passwordModel = new ChangePassword(LoggedUser.ID)
            {
                HasNotifications = HasNotifications
            };

            if (TempData["modelErrors"] != null)
            {
                Dictionary<string, string> modelErrors = TempData["modelErrors"] as Dictionary<string, string>;
                foreach (KeyValuePair<string, string> error in modelErrors)
                {
                    ModelState.AddModelError(error.Key, error.Value);
                }
            }

            return View("Password", passwordModel);
        }

        [HttpGet]
        public ActionResult Notifications()
        {
            NotificationsModel objNotificationsModel;
            if (TempData[NotificationsKey] == null)
            {
                objNotificationsModel = new NotificationsModel(this.LoggedUser, Context);
                objNotificationsModel.HasNotifications = HasNotifications;
            }
            else
            {
                Dictionary<string, int> dicNitificationsPara = (Dictionary<string, int>)TempData[NotificationsKey];

                objNotificationsModel = new NotificationsModel(this.LoggedUser.ID, dicNitificationsPara[PresetKey], Context);
                objNotificationsModel.objUser.Preset = dicNitificationsPara[PresetKey];
                objNotificationsModel.objUser.NotificationFrequency = dicNitificationsPara[NotificationFrequencyKey];
                objNotificationsModel.objUser.IncludeMyOwnActivity = dicNitificationsPara[IncludeMyOwnActivityKey] == 1;
            }

            if (TempData["modelErrors"] != null)
            {
                Dictionary<string, string> modelErrors = TempData["modelErrors"] as Dictionary<string, string>;
                foreach (KeyValuePair<string, string> error in modelErrors)
                {
                    ModelState.AddModelError(error.Key, error.Value);
                }
            }

            return View("Notifications", objNotificationsModel);

        }

        [HttpGet]
        public ActionResult OutOfOffice()
        {
            var outofofficemodel = new OutOfOfficeModel(LoggedUser.ID);

            outofofficemodel.HasNotifications = HasNotifications;
            outofofficemodel.OutOfOfficeData = UserBL.GetDataFromOutOfOffice(LoggedUser.ID, LoggedAccount.DateFormat1.Pattern, Context);
            return View("OutOfOffice", outofofficemodel);
        }

        [HttpGet]
        public ActionResult AddNewOutOfOffice(int? outOfOfficeId)
        {
            if (outOfOfficeId.HasValue)
            {
                var model = new AddNewOutOfOffice();
                var outOfOfficeDetails = UserBL.GetOutOfOfficeDetails((int)outOfOfficeId, LoggedAccount.DateFormat1.Pattern,Context);
                model.StartDate = GMGColorFormatData.GetFormattedDate(outOfOfficeDetails.FromDate, LoggedAccount.DateFormat1.Pattern);
                model.EndDate = GMGColorFormatData.GetFormattedDate(outOfOfficeDetails.ToDate, LoggedAccount.DateFormat1.Pattern);
                model.SubstituteUser = UserBL.GetUsersByAccount(LoggedUser, LoggedAccount, LoggedUserCollaborateRole, Context);
                model.Description = outOfOfficeDetails.Description;
                model.UserId = outOfOfficeDetails.SubstituteUserId;
                model.ID = (int)outOfOfficeId;

                DateTime toDate = DateTime.Now;
                DateTime fromDate = DateTime.Now;
                ViewBag.startDateYear = fromDate.Year;
                ViewBag.startDateMonth = fromDate.Month;
                ViewBag.startDateDay = fromDate.Day;
                ViewBag.endDateYear = toDate.Year;
                ViewBag.endDateMonth = toDate.Month;
                ViewBag.endDateDay = toDate.Day;
                ViewBag.MinStartDate = DateTime.Now;

                return View("AddNewOutOfOffice", model);
            }
            else {
                var model = new AddNewOutOfOffice();

                model.StartDate = GMGColorFormatData.GetFormattedDate(DateTime.UtcNow, LoggedAccount.DateFormat1.Pattern);
                model.EndDate = GMGColorFormatData.GetFormattedDate(DateTime.UtcNow, LoggedAccount.DateFormat1.Pattern);

                model.SubstituteUser = UserBL.GetUsersByAccount(LoggedUser, LoggedAccount, LoggedUserCollaborateRole, Context);

                DateTime toDate = DateTime.Now;
                DateTime fromDate = DateTime.Now;
                ViewBag.startDateYear = fromDate.Year;
                ViewBag.startDateMonth = fromDate.Month;
                ViewBag.startDateDay = fromDate.Day;
                ViewBag.endDateYear = toDate.Year;
                ViewBag.endDateMonth = toDate.Month;
                ViewBag.endDateDay = toDate.Day;
                ViewBag.MinStartDate = DateTime.Now;

                return View("AddNewOutOfOffice", model);
            }
        }


      
        #endregion

        #region POST Actions

        [HttpPost]
        public ActionResult Information(OwnerUser model)
        {
            try
            {
                string Input_String = model.FirstName + model.LastName + model.Username + model.MobileTelephoneNumber + model.HomeTelephoneNumber;

                if (!CheckIsValidHtml(Input_String) )
                {
                    return RedirectToAction("XSSRequestValidation", "Error");
                }
                if (!ValidateEmail(LoggedAccount, model.EmailAddress,LoggedUser.EmailAddress))
                {
                    //email already in use
                    ModelState.AddModelError("EmailAddress", Resources.Resources.reqEmailExist);
                    model.HasNotifications = HasNotifications;
                    model.InitializePermissions(LoggedUser.ID, LoggedAccount.ID, Context);
                    model.Languages = GMGColorDAL.Locale.GetLocalizeLocaleNames(Context);
                    return View("Index", model);
                }
                else if (!ValidateUserName(model.Username, LoggedUser.Username))
                {
                    //username already in use
                    ModelState.AddModelError("Username", Resources.Resources.reqUsernameExist);
                    model.HasNotifications = HasNotifications;
                    model.InitializePermissions(LoggedUser.ID, LoggedAccount.ID, Context);
                    model.Languages = GMGColorDAL.Locale.GetLocalizeLocaleNames(Context);
                    return View("Index", model);
                }
                else
                {
                    GMGColorDAL.User objUser = DALUtils.GetObject<GMGColorDAL.User>(LoggedUser.ID, Context);

                    using (TransactionScope ts = new TransactionScope())
                    {
                        objUser.GivenName = model.FirstName;
                        objUser.FamilyName = model.LastName;

src/gmgcozone/GMGColor/Views/PersonalSettings/AddNewOutOfOffice.cshtml
@model GMGColorDAL.CustomModels.AddNewOutOfOffice
@using GMGColor.Resources
@{
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
    Bundles.Reference("chosen");
    Bundles.Reference("datetimepicker");

    GMGColorDAL.Account objAcc = ViewBag.LoggedAccount;
    string dateFormat = objAcc.DateFormat1.Pattern;
}
<p class="breadcrumb">
    <a href="OutOfOffice">@Resources.lblPersonalOutofOffice</a>
</p>
@using (Html.BeginForm("AddNewOutOfOffice", "PersonalSettings", FormMethod.Post, new { @class = "form-horizontal", id = "formInformation" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ID)
    <div class="widget-content">
        <div class="control-group">
            <label class="control-label"> @Resources.lblSelectDeputyUsers &nbsp;</label>
            <div id="listSelectedAccount" class="control">
                @Html.DropDownListFor(model => model.UserId, new SelectList(Model.SubstituteUser, "ID", "Name", Model.UserId),new { @id = "selectedUser" })
            </div>
        </div>
        <div class="row-fluid">
            <div class="span3">
                <div class="control-group">
                    <label class="control-label">@Resources.lblStartDate</label>
                    <div class="controls">
                        <div class="input-append date-picker date" id="dtFromPicker" data-date-format="@dateFormat.ToLower()">
                            @Html.TextBoxFor(model => model.StartDate, new { @Value = String.Format("{0:" + dateFormat + "}", Model.StartDate), @size = "16", @class = "input-small", @readonly = "" })
                            <span class="add-on"><i class="icon-calendar"></i></span>
                        </div>
                        <span id="dtFromPickerAlert" class="help-inline" style="display: none;">@Resources.reqStartDate</span>
                    </div>
                </div>
            </div>
            <div class="span3">
                <div class="control-group">
                    <label class="control-label">@Resources.lblEndDate</label>
                    <div class="controls">
                        <div class="input-append date-picker date" id="dtToPicker" data-date="@String.Format("{0:" + dateFormat + "}", Model.EndDate)" data-date-format="@dateFormat.ToLower()">
                            @Html.TextBoxFor(model => model.EndDate, new { @Value = String.Format("{0:" + dateFormat + "}", Model.EndDate), @size = "16", @class = "input-small", @readonly = "" })
                            <span class="add-on"><i class="icon-calendar"></i></span>
                        </div>
                        <span id="dtToPickerAlert" class="help-inline" style="display: none;">@Resources.reqEndDate</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">@Resources.lblOutOfOfficeDescription</label>
            <div class="controls">
                @Html.TextBoxFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
              
        <div class="form-actions">
            <button class="btn btn-primary" id="btnSubmit" type="submit" name="action" value="AddNewOutOfOffice">@Resources.btnSave</button>
        </div>

        @if (ViewBag.error != null)
        {
        <div class="span5">
            <label style="color:red">@ViewBag.error</label>
        </div>
        }

    </div>

    
}
@{
    int startDateYear = int.Parse(ViewBag.startDateYear.ToString());
    int startDateMonth = int.Parse(ViewBag.startDateMonth.ToString());
    int startDateDay = int.Parse(ViewBag.startDateDay.ToString());
    int endDateYear = int.Parse(ViewBag.endDateYear.ToString());
    int endDateMonth = int.Parse(ViewBag.endDateMonth.ToString());
    int endDateDay = int.Parse(ViewBag.endDateDay.ToString());
    DateTime s = ViewBag.MinStartDate;

    DateTime minStartDate = DateTime.MinValue;
    if (ViewBag.MinStartDate != null)
    {
        minStartDate = (DateTime)ViewBag.MinStartDate;
    }
}
@section PageScript
        {
    <script type="text/javascript">

            $(function() {

                $('label.expired').each(function () {
                    $(this).parent('td').parent('tr').addClass('error');
                });

                var startDate = new Date(@startDateYear, @startDateMonth - 1, @startDateDay);
                var endDate = new Date(@endDateYear, @endDateMonth - 1, @endDateDay);

                $('#dtFromPicker').datepicker()
                    .on('changeDate', function(ev) {
                        if (ev.date.valueOf() > endDate.valueOf()) {
                            $('#dtFromPickerAlert').show();
                            $('#dtFromPicker').parent().parent().addClass("error");
                            $('#btnSubmit').attr('disabled', 'disabled');
                            startDate = new Date(ev.date);
                        }else{
                            $('.help-inline').hide();
                            $('.date').parent().parent().removeClass("error");
                            startDate = new Date(ev.date);
                            $('#btnSubmit').removeAttr('disabled');
                        }
                        $('#dtFromPicker').datepicker('hide');
                    });

                var minStartDate = new Date(@(minStartDate.Year), @(minStartDate.Month - 1), @(minStartDate.Day));
                $('#dtFromPicker').data('datepicker').setStartDate(minStartDate);


                $('#dtToPicker').datepicker()
                    .on('changeDate', function(ev) {

                        if (ev.date.valueOf() < startDate.valueOf()) {
                            $('#dtToPickerAlert').show();
                            $('#dtToPicker').parent().parent().addClass("error");
                            $('#btnSubmit').attr('disabled', 'disabled');
                            endDate = new Date(ev.date);
                        } else {
                            $('.help-inline').hide();
                            $('.date').parent().parent().removeClass("error");
                            endDate = new Date(ev.date);
                            $('#btnSubmit').removeAttr('disabled');
                        }
                        $('#dtToPicker').datepicker('hide');
                    });
                var minEndDate = new Date(@(minStartDate.Year), @(minStartDate.Month - 1), @(minStartDate.Day));
                $('#dtToPicker').data('datepicker').setStartDate(minEndDate);
                               
            });
       </script>

}

src/gmgcozone/GMGColor/Views/PersonalSettings/Index.cshtml
@model GMGColorDAL.CustomModels.OwnerUser
@using GMGColor.Resources
@{    
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
}
<div class="widget">
    <div class="widget-header">
        <h3>@ViewBag.Header@*&nbsp;<small>@ViewBag.HeaderSmall</small>*@</h3>
    </div>
    <!-- /widget-header -->
    <div class="widget-content">
        <div class="row-fluid">
            <div class="span3 accoutnSettingdNav">
                <ul class="nav nav-tabs nav-stacked">
                    <li class="active"><a href="Index">@Resources.lblPersonal</a></li>
                    <li><a href="Photo">@Resources.lblPersonalLabel</a></li>
                    <li><a href="Password">@Resources.lblPersonalPassword</a></li>
                    @if (Model.HasNotifications)
                    {
                        <li><a href="Notifications">@Resources.lblPersonalNotifications</a></li>
                    }
                   <li><a href="OutOfOffice">@Resources.lblPersonalOutofOffice</a></li>
                </ul>
            </div>
            <div class="span9">
                @using (Html.BeginForm("Information", "PersonalSettings", FormMethod.Post, new { @class = "form-horizontal", id = "formInformation" }))
                {             
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <legend>@Resources.lblPersonalInformation</legend>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblFirstName</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.FirstName)
                                @Html.ValidationMessageFor(model => model.FirstName)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblLastName</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.LastName)
                                @Html.ValidationMessageFor(model => model.LastName)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblPhone</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.HomeTelephoneNumber)
                                @Html.ValidationMessageFor(model => model.HomeTelephoneNumber)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblMobile</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.MobileTelephoneNumber)
                                @Html.ValidationMessageFor(model => model.MobileTelephoneNumber)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblUserName</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Username)
                                @Html.ValidationMessageFor(model => model.Username)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblEmail</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.EmailAddress)
                                @Html.ValidationMessageFor(model => model.EmailAddress)
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">@Resources.lblLanguage</label>
                            <div class="controls">
                                    @Html.DropDownListFor(model => model.SelectedLanguage, new SelectList(Model.Languages, "Key", "Value"))
                            </div>
                        </div>
                    </fieldset>
                    <fieldset>
                        <legend>@Resources.lblPersonalRole</legend>
                        <div class="control-group">
                            @{ Model.ModulePermisions.ForEach(m => m.ReadOnly = true); }
                            @Html.EditorFor(m=>m.ModulePermisions)
                        </div>
                    </fieldset>                    
                    @Html.HiddenFor(model => model.ID)
                    <div class="form-actions">
                        <input id="btnSaveChangesInformation" class="btn btn-primary" type="submit" value="@Resources.btnSaveChanges"  data-loading-text="@Resources.btnSaving"/>
                    </div>
                }
            </div>
        </div>
        <!-- /row-fluid -->
    </div>
    <!-- /widget-content -->
</div>
<!-- /widget -->

src/gmgcozone/GMGColor/Views/PersonalSettings/Notifications.cshtml
@model GMGColorDAL.CustomModels.NotificationsModel
@using GMGColor.Resources
@using GMGColorDAL
@{    
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
    GMGColorBusinessLogic.DbContextBL context = HttpContext.Current.Items[GMGColorDAL.DALUtils.DatabaseContext] as GMGColorBusinessLogic.DbContextBL;
}
<div class="widget">
    <div class="widget-header">
        <h3>@ViewBag.Header@*&nbsp;<small>@ViewBag.HeaderSmall</small>*@</h3>
    </div>
    <!-- /widget-header -->
    <div class="widget-content">
        <div class="row-fluid">
            <div class="span3">
                <div class="subnav accoutnSettingdNav">
                    <ul class="nav nav-tabs nav-stacked">
                        <li><a href="Index">@Resources.lblPersonal</a></li>
                        <li><a href="Photo">@Resources.lblPersonalLabel</a></li>
                        <li><a href="Password">@Resources.lblPersonalPassword</a></li>
                        @if (Model.HasNotifications)
                        {
                            <li class="active"><a href="Notifications">@Resources.lblPersonalNotifications</a></li>
                        }
                        <li><a href="OutOfOffice">@Resources.lblPersonalOutofOffice</a></li>
                    </ul>
                </div>
            </div>
            <div class="span9">
                @using (Html.BeginForm("", "PersonalSettings", FormMethod.Post, new { @class = "form-horizontal", id = "formNotifications" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.DisablePersonalNotifications)
                    if (Model.DisablePersonalNotifications)
                    {
                        <p class="validation-summary-errors">@Resources.lblYourPersonalNotificationsAreDisabled</p>
                    }
                 
                    <fieldset>
                        <legend>@Resources.lblNotification</legend>
                        <p>
                            @Resources.pharagraphPersonalSettingsNotification1</p>
                        <!-- Send Emails -->
                        <div class="control-group">
                            <label class="control-label">@Resources.lblSendEmail</label>
                            <div class="controls">
                                @Html.DropDownListFor(model => model.objUser.NotificationFrequency, new SelectList(GMGColorDAL.NotificationFrequency.GetLocalizedNotificationFrequencyNames(context), "Key", "Value", Model.objUser.NotificationFrequency), new { id = "ddlNFreq" })
                            </div>
                        </div>
                    </fieldset>
                    <div id="dvCustomiseNotificationEvents" style="@((GMGColorDAL.NotificationFrequency.GetNotificationFrequency(Model.objUser.NotificationFrequency, context) == GMGColorDAL.NotificationFrequency.Frequency.Never) ? "display:none;" : "display:block");">
                        <div class="controls" style="margin-top: 5px;">
                                <label class="checkbox">
                                    @Html.CheckBoxFor(model => model.objUser.IncludeMyOwnActivity)
                                    @Resources.lblIncludeMyOwnActivity
                                </label>
                            </div>
                        <fieldset>
                            <legend>@Resources.lblCustomiseYourNotificationEvents</legend>
                                @Html.ValidationSummary(true)
                            <p>
                                @Resources.pharagraphPersonalSettingsNotificatin2</p>
                            <div class="control-group">
                                <label class="control-label">@Resources.lblPreset</label>
                                <div class="controls">
                                    @Html.DropDownListFor(model => model.objUser.Preset, new SelectList(GMGColorDAL.Preset.GetLocalizedPresetNames(context), "Key", "Value", Model.objUser.Preset), new { onchange = "javascript:$('#btnPresetChange').click();" })
                                    <button type="submit" id="btnPresetChange" name="action" value="GetEvents" style="display: none">
                                        GetEvents</button>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            @{Dictionary<string, object> isDisabled = new Dictionary<string, object>();
                              if (GMGColorDAL.Preset.GetPreset(Model.objUser.Preset, context) != GMGColorDAL.Preset.PresetType.Custom)
                              {
                                  isDisabled.Add("disabled", "disabled");
                              }
                              List<int> modules = GMGColorBusinessLogic.ApplicationModuleBL.GetModulesExceptSysAdmin(context);
                              for (int j = 0; j < modules.Count(); j++)
                              {
                                  List<GMGColorDAL.CustomModels.NotificationsModel.EventGroup> evntGroups = Model.EventGroups.Where(t => t.ModuleID == modules[j]).ToList();
                                  if (evntGroups.Count > 0)
                                  {
                                        <legend>@GMGColor.Common.Utils.GetModuleNameByKey(GMGColorBusinessLogic.ApplicationModuleBL.GetModuleKeyById(modules[j], context))</legend>
                                      for (int i = 0; i < evntGroups.Count(); i++)
                                      {
                                        <div class="control-group">
                                            <label class="control-label">
                                                <strong>@evntGroups[i].Name</strong>
                                            </label>
                                            <div class="controls">
                                                @for (int n = 0; n < evntGroups[i].EventTypes.Count; n++)
                                                {
                                                    if (!(GMGColorConfiguration.AppConfiguration.IsHideFolderFunctionality))
                                                    {
                                                    <label class="checkbox groupevent">
                                                        @Html.CheckBoxFor(m => m.EventGroups[Model.EventGroups.IndexOf(evntGroups[i])].EventTypes[n].IsChecked, isDisabled)
                                                        @evntGroups[i].EventTypes[n].Name
                                                        @Html.HiddenFor(m => m.EventGroups[Model.EventGroups.IndexOf(evntGroups[i])].EventTypes[n].ID)
                                                    </label>
                                                    }
                                                }
                                            </div>
                                        </div>
                                      }
                                  }
                              }
                            }
                        </fieldset>
                    </div>
                    <div class="form-actions">
                        @Html.HiddenFor(model => model.objUser.ID)
                        <button type="submit" id="btnSaveChangesNotification" class="btn btn-primary" name="action"
                            value="SaveNotifications" data-loading-text="@Resources.btnSaving">@Resources.btnSaveChanges</button>
                    </div>
                }
            </div>
        </div>
        <!-- /row-fluid -->
    </div>
    <!-- /widget-content -->
</div>
<!-- /widget -->
@{
    int notificationNever = GMGColorDAL.NotificationFrequency.GetNotificationFrequency(GMGColorDAL.NotificationFrequency.Frequency.Never, context).ID;
}
<script type="text/javascript">
    var never = '@notificationNever';
    $('#ddlNFreq').change(function (e) {
        if ($(this).val() == never) {
            $('#dvCustomiseNotificationEvents').hide();
        }
        else {
            $('#dvCustomiseNotificationEvents').show();
        }
    });

    $(document).ready(function () {
        //disable all page controls if at least one "Disable personal notifications" option is set, for logged user,
        //from Account Settings > Global Notifications > Notificications Presets
        if ($('#DisablePersonalNotifications').val() == "True") {
            $("form :input").attr("disabled", "disabled");
        }
    });
</script>