src/gmgcozone/GMGColor/Controllers/StudioController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;
using GMGColor.Common;
using System.Transactions;
using AutoMapper;
using GMGColorBusinessLogic;
using GMGColorDAL;
using GMGColorDAL.CustomModels;
using GMG.CoZone.Collaborate.Services.Approval;
using GMG.CoZone.Collaborate.Interfaces.Proofstudio;
using GMG.CoZone.Collaborate.Interfaces;
using GMG.CoZone.Common.Interfaces;
using GMG.CoZone.Common;

namespace GMGColor.Controllers
{
    public class StudioController : BaseController
    {

        IApprovalPageService _approvalPageService = new ApprovalPageService();
        IApprovalService _approvalService;
        IApprovalUserViewInfoService _approvalUserViewInfoService;

        public StudioController(IApprovalService approvalService, IApprovalUserViewInfoService approvalUserViewInfoService, IDownloadService downlaodService, IMapper mapper) : base(downlaodService, mapper)
        {
            _approvalService = approvalService;
            _approvalUserViewInfoService = approvalUserViewInfoService;
        }

        #region GET Actions

        [HttpGet]
        //TODO check if this action is needed
        public ActionResult Index()
        {
            Session["SelectedApproval"] = null;
            Dashboard model = new Dashboard(this.LoggedAccount.ID, Context);
            model.IsWelcome = (Session["gmg_swscr_" + this.LoggedAccount.ID] != null) ? true : false;

            return View("Index", model);
        }

        [HttpGet]
        public ActionResult Html()
        {
            return GetResultURL(false);
        }

        [HttpGet]
        public ActionResult HtmlViewer(string apg, int? aid)
        {
            var approvalId = ApprovalBL.GetApprovalIdByGuid(apg, Context);
            CreateSessionVariables(approvalId, LoggedUser.ID);

            //if(aid != null && aid > 0)
            //{
                CreateAnnotationSession(aid);
            //}

            if (Session[GMG.CoZone.Common.Constants.ApprovalsTopLink + this.LoggedUser.ID.ToString()] != null && 
                    (Session[GMG.CoZone.Common.Constants.ApprovalsTopLink + this.LoggedUser.ID.ToString()] != null ? 
                    int.Parse(Session[GMG.CoZone.Common.Constants.ApprovalsTopLink + this.LoggedUser.ID.ToString()].ToString().Trim()) == -8 ?
                    Session[GMG.CoZone.Common.Constants.OutOfOfficeUser] != null : false : false))
            {
                return RedirectToAction("RedirectHtml5");                
            }

            if (!CanAccessApproval(approvalId, Approval.ApprovalOperation.ViewApproval))
            {
                return RedirectToAction("Unauthorised", "Error");
            }

            return RedirectToAction("RedirectHtml5");
        }

        private void CreateAnnotationSession(int? annotationID)
        {
            Session["AnnotationAtUserInComment"] = annotationID;
        }
        private void CreateSessionVariables(int approvalId, int loggeUserId)
        {
            string sessionKey = (new Random()).Next(1000, 9999).ToString();
            Session["SessionKey"] = sessionKey;

            Session["StudioApproval_" + sessionKey] = new List<int> { approvalId };
            Session["StudioLoggedUser_" + sessionKey] = loggeUserId;           
        }

        [HttpGet]
        public ActionResult HtmlViewerExternal(string apg, string sessionKey)
        {
            Session["SessionKey"] = sessionKey;

            var approval_Id = new List<int> { ApprovalBL.GetApprovalIdByGuid(apg, Context) };
            var user_Id = ApprovalBL.GetUserIdByCollaborateAPISessionKey(sessionKey, Context);
            Session["StudioApproval_" + sessionKey] = approval_Id;
            Session["StudioLoggedUser_" + sessionKey] = ApprovalBL.GetUserIdByCollaborateAPISessionKey(sessionKey, Context);

            return GetResultURLForAPIUsers(approval_Id[0] , user_Id);
            //return RedirectToAction("RedirectHtml5");
        }

        [HttpGet]
        public ActionResult HtmlViewerCompareVersions(string v1Guid, string v2Guid, string sessionKey)
        {
            Session["SessionKey"] = sessionKey;

            Session["StudioVersionsToCompare_" + sessionKey] = new List<int> { ApprovalBL.GetApprovalIdByGuid(v1Guid, Context), ApprovalBL.GetApprovalIdByGuid(v2Guid, Context) };
            Session["StudioLoggedUser_" + sessionKey] = ApprovalBL.GetUserIdByCollaborateAPISessionKey(sessionKey, Context);

            return RedirectToAction("RedirectHtml5");
        }

        [HttpGet]
        public ActionResult Flex()
        {
            return GetResultURL(false);
        }

        [HttpGet]
        public ActionResult Redirect()
        {
            return GetResultURL(true);
        }

        [HttpGet]
        public ActionResult RedirectHtml5(bool? isExternal)
        {
            return GetResultURL(isExternal.GetValueOrDefault());
        }

        #endregion

        #region POST Actions

        #endregion

        #region Methods

        private ActionResult GetResultURL(bool isExternal)
        {
            string sessionKey = ((Session["SessionKey"] != null) ? Session["SessionKey"].ToString() : "0");
            string PSSessionKey = Guid.NewGuid().ToString();
            try
            {
                List<int> approvalIds;

                List<int> explicitVersions = ExplicitVersionsToCompare(sessionKey);
                if (explicitVersions.Any())
                {
                    approvalIds = GetApprovalsIdsForVersionsIds(explicitVersions);
                    @ViewBag.VersionsIds = string.Join(",", explicitVersions.ToArray());
                    @ViewBag.ExplicitVersionsToCompare = @ViewBag.VersionsIds;
                }
                else
                {
                    @ViewBag.ExplicitVersionsToCompare = "";

                    approvalIds = Session["StudioApproval_" + sessionKey] as List<int>;
                    int selectedApprovalIDFromProof = ApiController.GetSelectedApprovalID();
                    if (selectedApprovalIDFromProof > 0)
                    {
                        List<int> approvalid = new List<int>();
                        approvalid.Add(selectedApprovalIDFromProof);
                        approvalIds = approvalid;
                        ApiController.SetSelectedApprovalIDNull();
                    }
                    int SelectedProjectFolderID = Session[Constants.SelectedProjectId] != null ? int.Parse(Session[Constants.SelectedProjectId].ToString()) : 0;
                    ViewBag.IsfromProjectFolder = SelectedProjectFolderID > 0 ? true : false;
                    ViewBag.ProjectFolderID = 0;
                    if (ViewBag.IsfromProjectFolder)
                    {
                        int projectFolderID = ProjectFolderBL.GetProjectFolderIdFromApproval(approvalIds[0]);
                        ViewBag.ProjectFolderID = SelectedProjectFolderID == projectFolderID ? SelectedProjectFolderID : projectFolderID;
                    }
                    // In case approval ids are missing (call is made from UI)
                    if (approvalIds != null &&
                        // In case approval ids are missing (call is made from API)
                        (approvalIds.Count > 0 && !approvalIds.Any(apId => apId == 0)))
                    {
                        @ViewBag.VersionsIds = string.Join(",", ApiBL.GetVersionsIds(approvalIds).ToArray());
                    }
                    else
                    {
                        return StudioWithLastVisitedApproval(LoggedUser.ID);
                    }                    
                }
                int scrollTop = ApiController.GetScrollTop();
                ViewBag.ScrollTop = scrollTop > 0 ? scrollTop : 0;
                ApiController.SetScrollTopNull();
                List<string> selectedApprovalTypes = ApiController.GetSelectedApprovalType();
                ViewBag.SelectedApprovalTypes = string.Empty;
                if (selectedApprovalTypes != null && selectedApprovalTypes.Count > 0)
                {
                    ApiController.SetSelectedApprovalTypesNull();
                    string approvalTypes = string.Empty;
                    foreach(var type in selectedApprovalTypes)
                    {
                        if(approvalTypes == string.Empty)
                        {
                            approvalTypes = type;
                        } else
                        {
                            approvalTypes = approvalTypes + "," + type;
                        }
                    }
                    ViewBag.SelectedApprovalTypes = approvalTypes;
                }
                var approvalId = approvalIds[0];
                ViewBag.selectedHtmlPageId = 0;
                @ViewBag.ApprovalFirstPageId = _approvalPageService.GetApprovalFirstPageId(approvalId);
                @ViewBag.ApprovalType = _approvalService.GetApprovalType(approvalId);
                if(ViewBag.ApprovalType == Approval.ApprovalTypeEnum.Zip)
                {
                    var  result = ApiController.GetHtmlPageId();
                    var pageID = ApiBL.GetHtmlPageId(approvalId);
                    if (pageID > 0)
                    {
                        ViewBag.selectedHtmlPageId = pageID;
                    } else
                    {
                        ViewBag.selectedHtmlPageId = result;
                    }
                    ApiController.SetPageIdNull();
                }

                @ViewBag.ApprovalId = approvalIds[0];
                @ViewBag.Approvals = string.Join(",", approvalIds.ToArray());
                


src/gmgcozone/GMGColor/Views/Studio/DeliverAddJobFromProofStudio.cshtml
@model GMGColorDAL.CustomModels.Deliver.AddInstance
@using GMGColor.FileUpload
@using GMGColor.Resources;
@using GMG.CoZone.Common;
@using GMGColorDAL

@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger" role="alert">
        <strong>@Resources.lblWarning :</strong>
        @Model.ErrorMessage
    </div>
}

@Html.ValidationSummary(true)
<input type="hidden" id="SelectedApprovalsPageCounts" data-val="false" />
<div id="detailsContainer"><h3>@Resources.lblDeliverIndexPopupDetails</h3><hr/></div>
<div class="control-group">
    <label class="control-label large-label">@Resources.lblDeliverIndexPopupColorProofServer</label>
    <div class="controls dropdown">
        @Html.DropDownListFor(m => m.SelectedCPServerId, new SelectList(Model.ListServers, "ID", "SystemName"), Resources.lblDeliverIndexSelectAColorProofServer, new { @class = "czn-select" })
        @Html.ValidationMessageFor(m => m.SelectedCPServerId)
    </div>
</div>
<div class="control-group">
    <label class="control-label">@Resources.lblDeliverIndexPopupColorProofWorkflow</label>
    <div class="controls dropdown">
        @Html.DropDownListFor(m => m.SelectedCPWorkflowId, new SelectList(Model.ListWorkflows, "ID", "Name"), Resources.lblDeliverIndexSelectAColorProofWorkflow, new { @class = "czn-select" })
        @Html.ValidationMessageFor(m => m.SelectedCPWorkflowId)
    </div>
</div>
<div class="control-group">
    <label class="control-label">@Resources.lblDeliverIndexPopupColorProofPages</label>
    <div class="controls" id="pages">
        <div class="pages-row PagesSingle">
            @Html.RadioButtonFor(m => m.PagesRadioButton, (int)PagesSelectionEnum.Single, new { id = "Pages_Single", @class = "pages-ctrl-left", @checked = "checked" })
            <label class="radioLabel" for="Pages_Single">@Resources.lblDeliverIndexPopupPagesSingle</label>
        </div>
        <div class="pages-row PagesRange">
            @Html.RadioButtonFor(m => m.PagesRadioButton, (int)PagesSelectionEnum.Range, new { id = "Pages_Range", @class = "pages-ctrl-left" })
            <label class="radioLabel" for="Pages_Range" class="pages-ctrl-left">@Resources.lblDeliverIndexPopupPagesRange</label>
            @Html.TextBoxFor(m => m.PagesRangeValue, new { @class = "form-control input-sm", @readonly = "readonly" })
            
        </div>
        <div class="pages-row">
            @Html.RadioButtonFor(m => m.PagesRadioButton, (int)PagesSelectionEnum.All, new { id = "Pages_All", @class = "pages-ctrl-left" })
            <label class="radioLabel" id="page_all_label"  for="Pages_All">@Resources.lblDeliverIndexPopupPagesAll</label>
        </div>
        @Html.ValidationMessageFor(m => m.PagesRangeValue)
        @Html.ValidationMessageFor(m => m.PagesRadioButton)

        @Html.HiddenFor(m => m.PagesRangeHiddenField)
        @Html.ValidationMessageFor(m => m.PagesRangeHiddenField)
        
        @Html.HiddenFor(m => m.PagesRangeMaxPageCountHiddenField)
        @Html.ValidationMessageFor(m => m.PagesRangeMaxPageCountHiddenField)
        <input type="hidden" data-val="false" id="lblPagesCountInfoResource" value="@Resources.lblPagesCountInfo"/>
        <div id="lblMaxPagesCount"></div>
    </div>
</div>
@if (ViewBag.DeliverRole != GMGColorDAL.Role.RoleName.AccountContributor)
{
    <div>
        <div id="notificationContainer"><h3>@Resources.lblNotification <small class="text-muted">@Resources.lblChooseWhoWillBeAbleToViewJob</small></h3></div>
        <hr/>
        @{Html.RenderAction("Share", "Widget", new { @showPanel = true, @isFromDeliver = true, @showPopup = !Model.ShowUploader });}
        <!-- / Sahre -->
        <div class="collaboratorshare-fields control-group row-fluid">
            <div class="controls">
                <h6>@Resources.lblMessageDeliverNotification</h6>
                @Html.TextAreaFor((mdl => mdl.OptionalMessage), new { @id = "deliverMessage", @class = "message span5 message-option-input", @cols = "20", @rows = "4", @tabindex = "7" })
            </div>
        </div>
    </div>
}
<div id="detailsContainer"><h3>@Resources.lblDeliverIndexPopupSettings</h3><hr/></div>
<div class="control-group">
    <div class="@string.Format("{0}", Model.ShowUploader ? "controls" : string.Empty)">
        <div class="pages-row">
            @Html.CheckBoxFor(m => m.IncludeProofMetaInformation, new { id = "IncludeProofMetaInformation", @class = "pages-ctrl-left" })
            <label id="IncludeProofMetaInformation" for="IncludeProofMetaInformation" class="pages-ctrl-left">@Resources.lblDeliverIndexPopupIncludeProofMetaInformation</label>
            @Html.ValidationMessageFor(m => m.IncludeProofMetaInformation)
        </div>
        <div class="pages-row">
            @Html.CheckBoxFor(m => m.LogProofControlResults, new { id = "LogProofControlResults", @class = "pages-ctrl-left" })
            <label id="LogProofControlResults" for="LogProofControlResults" class="pages-ctrl-left">@Resources.lblDeliverIndexPopupLogProofControlResults</label>
            @Html.ValidationMessageFor(m => m.LogProofControlResults)
        </div>
    </div>
</div>

@Html.Hidden("getWorkflowsAction", @Url.Action("GetWorkflows", "Deliver"))
@Html.Hidden("ldgLbl", @Resources.lblLoading)

<script src="@Url.Content("~/Scripts/DeliverAddJob.js")"></script>



src/gmgcozone/GMGColor/Views/Studio/Flex.Tablet.cshtml
@using GMGColor.Controllers
@using GMGColorDAL
@using GMGColorDAL.CustomModels

@{
    GMGColorBusinessLogic.DbContextBL context = HttpContext.Current.Items[GMGColorDAL.DALUtils.DatabaseContext] as GMGColorBusinessLogic.DbContextBL;

    string colorTheme = "default";
    int accountId = 0;
    string accountRegion = string.Empty;

    GMGColorDAL.Account objAccount = null;
    if (Session["gmg_aid"] != null)
    {
        accountId = int.Parse(Session["gmg_aid"].ToString());
        objAccount = DALUtils.GetObject<GMGColorDAL.Account>(accountId, context);

        accountRegion = objAccount.Region;
    }

    GMGColorDAL.User objUser = null;
    if ((objAccount != null && objAccount.ID > 0) && (Session["gmg_uid"] != null))
    {
        objUser = DALUtils.GetObject<GMGColorDAL.User>(int.Parse(Session["gmg_uid"].ToString()), context);
    }

    AccountSupport accSupModel = null;
    if (objUser != null && objUser.ID > 0 && objAccount != null)
    {
        accSupModel = new AccountSupport(objUser, objAccount.Region, GMGColorDAL.User.GetUserTempFolderPath(objUser.ID, objAccount.ID, objAccount.Region));
    }

    if (objAccount != null)
    {
        var colorScheme = (Theme.ColorScheme)ViewBag.LoggedAccountTheme;
        switch (colorScheme)
        {
            case GMGColorDAL.Theme.ColorScheme.Splash:
                colorTheme = "pink";
                break;
            case GMGColorDAL.Theme.ColorScheme.Juicy:
                colorTheme = "green";
                break;
            case GMGColorDAL.Theme.ColorScheme.Fresh:
                colorTheme = "blue";
                break;
            case GMGColorDAL.Theme.ColorScheme.Moody:
                colorTheme = "white";
                break;
            case GMGColorDAL.Theme.ColorScheme.Default:
            default:
                colorTheme = "default";
                break;
        }
    }

    string version = string.Empty;
    if (Session["VERSION"] == null)
    {
        version = typeof(GMGColor.Controllers.HomeController).Assembly.GetName().Version.ToString();
        Session[AuthController.VersionSessionKey] = version;
    }
    else
    {
        version = Convert.ToString(Session["VERSION"]);
    }
}
<!DOCTYPE html>
<html>
<head>
<title>@ViewBag.SiteName</title>
    <meta name="description" content="" />
    <meta name="author" content="GMG Color" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="@GMGColorConfiguration.AppConfiguration.DataFolderName(accountRegion), @GMGColorConfiguration.AppConfiguration.PathToDataFolder(accountRegion), @GMGColorConfiguration.AppConfiguration.ApprovalJobQueueName">
    <meta http-equiv="Content-Type" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="@Url.Content("~/Content/ProofStudio/tablet/app.min.css")" rel="stylesheet" media="screen" />
    <script src="@Url.Content("~/Content/ProofStudio/tablet/config.min.js")"></script>
    <script src="@Url.Content("~/Content/ProofStudio/tablet/vendor.min.js")"></script>
    <script src="@Url.Content("~/Content/ProofStudio/tablet/app.min.js")"></script>

    @switch (colorTheme)
    {
        case "green":
        {
            <link rel="stylesheet/less" type="text/less" href="/Content/less/themes/theme-green.less" />
            break;
        }
        case "pink":
        {
            <link rel="stylesheet/less" type="text/less" href="/Content/less/themes/theme-pink.less" />
            break;
        }
        case "blue":
        {
            <link rel="stylesheet/less" type="text/less" href="/Content/less/themes/theme-blue.less" />
            break;
        }
        case "white":
        {
            <link rel="stylesheet/less" type="text/less" href="/Content/less/themes/theme-white.less" />
            break;
        }
        default:
        {
            <link rel="stylesheet/less" type="text/less" href="/Content/less/themes/theme-default.less" />
            break;
        }
    }
    <script src="/Content/js/less/less.min.js" type="text/javascript"></script>

    @{
        string sessionKey = ((Session["SessionKey"] != null) ? Session["SessionKey"].ToString() : "0");
        string sessionTimeOut = (Session["STO"] != null) ? Session["STO"].ToString() : "0";
    }
    <script>
        jQuery.extend(window.ENV, {
            approval_id: '@((Session["StudioApproval_" + sessionKey] != null) ? Session["StudioApproval_" + sessionKey].ToString() : "0")',
            hostname: '@ViewBag.RestApiHostURL',
            namespace: '@ViewBag.Namespace',
            key: '@ViewBag.SecurityKey',
            user_key: '@ViewBag.UserKey',
            URL: '@((Session["StudioReturnURL_" + sessionKey] != null) ? Session["StudioReturnURL_" + sessionKey].ToString() : "/Auth/Login")',
            default_locale: 'en-US',
        });            
    </script>
    @{
        string logoPath = accountId > 0 ? @GMGColorDAL.Account.GetLogoPath(accountId, GMGColorDAL.Account.LogoType.HeaderLogo, context) : "/content/img/nologo-122px-33px.png";
    }
    <style type="text/css">
        .czn-logo {
            background: url('@logoPath') no-repeat 50% 50%;
        }
    </style>

</head>
<body>
  <!--[if lte IE 8]>
    <p class="browsehappy">
      You are using an <strong>outdated</strong> browser. Please
      <a href="http://browsehappy.com/">upgrade your browser</a>
      to improve your experience.
    </p>
  <![endif]-->

  <script>
      window.App = require('appkit/main')['default']('appkit');
  </script>
    <div class="modal czn-loading-screen" id="czn-loading-screen" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Loading...</h4>
                </div>
                <div class="modal-body">
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

src/gmgcozone/GMGColor/Views/Studio/Index.cshtml
@model GMGColorDAL.CustomModels.Dashboard
@{    
    Layout = "~/Views/Shared/_LayoutApplication.cshtml";
}
<div class="widget">
    <div class="widget-header">
        <h3>@ViewBag.Header</h3>
    </div>
    <!-- /widget-header -->
    <div class="widget-content">
        <div class="row-fluid">
            @using (Html.BeginForm(string.Empty, "Studio", FormMethod.Post, new { id = "formMain", @class = "form-vertical" }))
            {
                @Html.AntiForgeryToken()

            }
        </div>
        <!-- /row-fluid -->
    </div>
    <!-- /widget-content -->
</div>
<!-- /widget -->
@if (Model.IsWelcome)
{
    @Html.Partial("AccountWelcome", Model.objAccount)
    <script type="text/javascript">
        this.modelDialog = 'modalDialogWelcome';
    </script>
}

src/gmgcozone/GMGColor/Views/Studio/ModalSubmitToDeliver.cshtml
@using GMGColor.Resources
@using GMGColor.HtmlHelpers
@using GMGColorDAL.CustomModels
@model GMGColorDAL.CustomModels.Deliver.AddInstance

@Html.Hidden("hdnGetApprovalsPageCount", @Url.Action("GetApprovalsPageCount", "Approvals")) 
@Html.Hidden("hdnLoadSubmitToDeliverPopup", @Url.Action("LoadSubmitToDeliverPopup", "Approvals")) 


@{
    Bundles.Reference("proofstudio-sendJobToDeliverStyles");
    Bundles.Reference("proofstudio-sendJobToDeliverScripts");
}

<div id="modalDialogSubmitToDeliverFromPS" class="modal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    @using (Ajax.BeginForm("AddDeliverJobFromPS", "Approvals", new { }, new AjaxOptions() { OnComplete = "AddDeliverJobCompleted" }, new { id = "formAddDeliverJob", @class = "form-horizontal", autocomplete = "off" }))
    {
            @Html.AntiForgeryToken()
            <div class="modal-sm modal-position">
                <div class="modal-content" style="width: 560px">
                    <div class="modal-header">
                        <h3 class="modal-title" style="width: auto; display: inline">@Resources.btnAddNewDeliverJob</h3>
                        <a href="javascript:void(0);" class="close" data-dismiss="modal" title="@Resources.btnClose" widget-toggle="closedeliverpopup" onclick="ResetDeliverModel()";>&times;</a>
                    </div>
                     <div class="modal-body">
                        @*Filled by Asynchronous call*@
                        <img id="deliverPopUpLoading" class="hidden" src="/Content/img/loading-icon.gif" alt="@Resources.lblLoading" />
                     </div>
                     <div class="modal-footer">
                        <button class="btn btn-primary" type="submit" id="AddDeliverJob" data-loading-text="@Resources.btnSaving">@Resources.btnAddColorProofInstance</button>
                    </div>
                </div>
                @Html.Hidden("SelectedApprovalJobs", ViewData["approval_Id"], new { @data_val = false })  
            </div>
    }
</div>